### ISSUE TITLE
Hello, would you please provide the dataset of MIRFLIKCR and NUSWIDE? And I wonder whether the dataset is randomly divided? hope your answer.

### ISSUE THREAD

**Issue by Junyanzhang** [penghu-cs/UCCH#1]
Hello, would you please provide the dataset of MIRFLIKCR and NUSWIDE? And I wonder whether the dataset is randomly divided? hope your answer.

**Comment by ZCyueternal** [comment]
I have the same question....

**Comment by penghu-cs** [comment]
Thanks a lot for your attention. The randomly divided data could be downloaded from pan.baidu.com.

MIRFLICKR25K:
link: https://pan.baidu.com/s/1vgqIfGeD8-KxXNekoQ-6cw
password: ubwu

NUS-WIDE (top-10 concept):
link: https://pan.baidu.com/s/1mlCVxiSsjp7pcQeQQX-yDw
password: ru9j

**Comment by ZCyueternal** [comment]
I would like to express my sincere thanks to you. It's useful and I am very interested in your work.

**Comment by Junyanzhang** [comment]
> Thanks a lot for your attention. The randomly divided data could be downloaded from pan.baidu.com.
> 
> MIRFLICKR25K: link: https://pan.baidu.com/s/1vgqIfGeD8-KxXNekoQ-6cw password: ubwu
> 
> NUS-WIDE (top-10 concept): link: https://pan.baidu.com/s/1mlCVxiSsjp7pcQeQQX-yDw password: ru9j

Are the other two data sets IAPR TC-12 and MSCOCO also available？ thank you again

**Comment by penghu-cs** [comment]
Thanks a lot for your attention. The data are available at:
IAPR-TC12:
link: https://pan.baidu.com/s/1c779W9I_E3szolBcPc_uTQ?pwd=f2ij
password: f2ij

MSCOCO:
link: https://pan.baidu.com/s/1h7tje0LdSH2x7pZxyvS3-A?pwd=s286
password: s286
