### ISSUE TITLE
During validation, are the retrieval set and the query set the same

### ISSUE THREAD

**Issue by Junyanzhang** [penghu-cs/UCCH#10]
(retrieval_imgs, retrieval_txts, retrieval_labs) = eval(retrieval_loader)
        if is_eval:
            query_imgs, query_txts, query_labs = retrieval_imgs[0: 2000], retrieval_txts[0:2000], retrieval_labs[0: 2000]
            retrieval_imgs, retrieval_txts, retrieval_labs = retrieval_imgs[0: 2000], retrieval_txts[0: 2000], retrieval_labs[0:2000]

**Comment by penghu-cs** [comment]
Yes. This aims to speed up the validation process.
