### ISSUE TITLE
关于mirflickr25k数据集的问题

### ISSUE THREAD

**Issue by yuka-helium** [penghu-cs/UCCH#13]
您好，请问可以给出mirflickr25k-iall-vgg-rand.mat的数据集吗？非常感谢

**Comment by penghu-cs** [comment]
您好，UCCH/data/README.md 下有全部数据集的下载链接，感谢您的关注。

**Comment by gfdbm** [comment]
您好，在给出来的数据集下载链接里面没有mirflickr25k-iall-vgg-rand.mat，是文件已经损坏了吗

**Comment by kuaile258890** [comment]
> 您好，在给出来的数据集下载链接里面没有mirflickr25k-iall-vgg-rand.mat，是文件已经损坏了吗

可以用mirflickr25k-iall-vgg.mat改名。我试验过可以复现出论文结果

**Comment by gfdbm** [comment]
> > 您好，在给出来的数据集下载链接里面没有mirflickr25k-iall-vgg-rand.mat，是文件已经损坏了吗
> 
> 可以用mirflickr25k-iall-vgg.mat改名。我试验过可以复现出论文结果

您复现出来的结果是多少，我怎么跑出来百分之八十多

**Comment by kuaile258890** [comment]
> > > 您好，在给出来的数据集下载链接里面没有mirflickr25k-iall-vgg-rand.mat，是文件已经损坏了吗
> > 
> > 
> > 可以用mirflickr25k-iall-vgg.mat改名。我试验过可以复现出论文结果
> 
> 您复现出来的结果是多少，我怎么跑出来百分之八十多

在最底下的issue中有解释，似乎是代码出现了问题， 用@JamalzzJ 的解释修改代码可以解决，和论文结果基本一致。但仅限于使用作者提供的vgg提取的权重，用raw data我完全无法复现结果。我用vgg权重复现的结果可以参考最上面我提的issue

**Comment by kuaile258890** [comment]
> > > 您好，在给出来的数据集下载链接里面没有mirflickr25k-iall-vgg-rand.mat，是文件已经损坏了吗
> > 
> > 
> > 可以用mirflickr25k-iall-vgg.mat改名。我试验过可以复现出论文结果
> 
> 您复现出来的结果是多少，我怎么跑出来百分之八十多

在最底下的回复中有解释，似乎是代码出现了问题， 用@JamalzzJ 的解释修改代码可以解决，和论文结果基本一致。但仅限于使用作者提供的vgg提取的权重，用raw data我完全无法复现结果

> > > 您好，在给出来的数据集下载链接里面没有mirflickr25k-iall-vgg-rand.mat，是文件已经损坏了吗
> > 
> > 
> > 可以用mirflickr25k-iall-vgg.mat改名。我试验过可以复现出论文结果
> 
> 您复现出来的结果是多少，我怎么跑出来百分之八十多

若您按上面的方法修改代码后，在raw data的方法能够复现出论文结果，希望能够通知我一下，谢谢。祝好

**Comment by penghu-cs** [comment]
将src/cmdataset.py文件里，三个路径里的-rand去掉即可。抱歉，上传文件的时候修改了文件名，忘了更新代码。

关于raw data，可以增大warmup_epoch即可，比如：3、5等。
