### ISSUE TITLE
关于UCCH中fx_calc_map_multilabel_k函数的问题

### ISSUE THREAD

**Issue by MarvinKuai** [penghu-cs/UCCH#15]
你好，我在计算map@all时，对UCCH.py中fx_calc_map_multilabel_k函数有一些疑惑。
    dist = scipy.spatial.distance.cdist(query, retrieval, metric)
    ord = dist.argsort()
    numcases = dist.shape[0]
    if k == 0:
        k = numcases
     当k=0时，是不是意味着map@all,但是 numcases = dist.shape[0]，这个显然不是。这个返回了query数量，但是k需要等于retrieval数量

**Comment by penghu-cs** [comment]
感谢您指出问题。虽然这里写错了K，但是具体计算的时候没有用到K，还是在整个retrieval上计算的，没有问题。可以把这两行代码删除。

**Comment by penghu-cs** [comment]
感谢您指出问题。可以把“[0: k]”删除，或者将“k = numcases”改为“k = dist.shape[1]”，即为map@all。
