### ISSUE TITLE
coco数据集运行有问题，其他数据集没问题

### ISSUE THREAD

**Issue by 19200308yst** [penghu-cs/UCCH#17]
![Uploading T9[(@]FRMJEFG2Q0NA2])I5.png…]()

**Comment by 19200308yst** [comment]
是报Invalid argument，是用cpu运行的代码。请问是什么问题啊？

**Comment by penghu-cs** [comment]
我没遇到过类似的错误。请问是不是数据集的名不对？

**Comment by 19200308yst** [comment]
代码是可以运行的，这个代码是我的老师修改过的，因为我是拿抽取好特征的数据集运行的。然后我老师那边是用gpu跑的，都是没问题的，我用的cpu。老师说可能是coco数据集对我的电脑来说太大了，但是取10000的训练数据都依旧会报错，请问您能有什么想法关于这个问题？十分感谢您的回复！！








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "penghu-cs/UCCH"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月29日(星期四) 下午4:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [penghu-cs/UCCH] coco数据集运行有问题，其他数据集没问题 (Issue #17)





 
我没遇到过类似的错误。请问是不是数据集的名不对？

**Comment by penghu-cs** [comment]
抱歉，我们没有尝试过在cpu上跑。您可以查查相关的文档，看看有没有解决方法。
