### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by shx141999** [penghu-cs/UCCH#2]
I think this paper is very good. Could you please share your dataset？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by penghu-cs** [comment]
Thanks a lot for your attention. The datasets could be downloaded from https://github.com/jiangqy/DCMH-CVPR2017/tree/master/DCMH_matlab/DCMH_matlab
Thanks.

**Comment by shx141999** [comment]
Thank you very much for your response. I personally like this paper very much and want to run your code, so I am looking forward to your data set, thank you

**Comment by shx141999** [comment]
>
