### ISSUE TITLE
Some questions about the memory-bank

### ISSUE THREAD

**Issue by kuaile258890** [penghu-cs/UCCH#20]
Hello, in your UCCH, you adopted a momentum update approach similar to MoCo. However, in my experiments, I found that the hyperparameter K has little impact on performance. I'm wondering if you have encountered this issue in your experiments. I'm not sure if this result is unique to my machine. Would choosing a smaller K or considering the removal of the memory bank further enhance efficiency? Here are my experimental results (MIRFLICKR-25K):

128bit
K:256 Img2Txt: 0.768999        Txt2Img: 0.742612       Avg: 0.755805
K:512 Img2Txt: 0.769573        Txt2Img: 0.74065        Avg: 0.755112
K:1024 Img2Txt: 0.769944        Txt2Img: 0.740525       Avg: 0.755235
K:2048 Img2Txt: 0.768865        Txt2Img: 0.742405       Avg: 0.755635
K:4096 Img2Txt: 0.768886        Txt2Img: 0.742765       Avg: 0.755825

16bit：
K:256 Img2Txt: 0.734208        Txt2Img: 0.70426        Avg: 0.719234
K:512 Img2Txt: 0.731359        Txt2Img: 0.702105       Avg: 0.716732
K:1024 Img2Txt: 0.7338          Txt2Img: 0.703864       Avg: 0.718832
k:2048 Img2Txt: 0.734707        Txt2Img: 0.704817       Avg: 0.719762
K:4096 Img2Txt: 0.734259        Txt2Img: 0.706975       Avg: 0.720617

32bit：
K:256 Img2Txt: 0.759809        Txt2Img: 0.734137       Avg: 0.746973
K:512 Img2Txt: 0.759853        Txt2Img: 0.734565       Avg: 0.747209
K:1024 Img2Txt: 0.760381        Txt2Img: 0.735373       Avg: 0.747877
K:2048 Img2Txt: 0.76008         Txt2Img: 0.73348        Avg: 0.74678
K:4096 Img2Txt: 0.759792        Txt2Img: 0.734154       Avg: 0.746973

**Comment by penghu-cs** [comment]
It is an interesting finding. We have not encountered this phenomenon in our experiments. It is intriguing to explore further. Thanks a lot for your attention.

**Comment by kuaile258890** [comment]
> It is an interesting finding. We have not encountered this phenomenon in our experiments. It is intriguing to explore further. Thanks a lot for your attention.

Thank you for your reply. At the same time, I would like to ask, do you think inconsistencies may arise in the memory bank? In MoCo, the slight differences brought by momentum updates might not have a significant impact. However, in your work on UCCH, the values updated by momentum are further processed through the sign function to produce binary codes of -1 and 1. Given that these continuous values, due to normalization, usually have relatively small magnitudes (e.g., 0.01), this could lead to inconsistencies near zero being amplified by the sign function (for example, the minor difference between -0.001 and 0.001 would result in a disparity between -1 and 1 after the sign function is applied), could this be a potential limitation in UCCH?

**Comment by penghu-cs** [comment]
Sorry for the late reply. I believe that the inconsistency you mentioned will not significantly impact the performance. When calculating the Hamming similarity (inner product), the inconsistency caused by values with the same sign is much less impactful than those with different signs. Therefore, the use of the sign function has not introduced a significant inconsistency. It remains consistent with traditional contrastive learning while favoring binarization.
