### ISSUE TITLE
about the batch_size and warmup_epoch

### ISSUE THREAD

**Issue by RIU-13** [penghu-cs/UCCH#23]
仅仅把batch_size调成96，map就只有0.59，且不上升，96作为batch_size也不少了？是要同步更改哪些配置吗？

**Comment by RIU-13** [comment]
并且warmup_epoch是将vgg这类backbone冻结，只训特征网络，且对NCEaverage的动量产生影响，改变warmup_epoch的数量会对最终结果产生影响的原理是什么呢？按照我的训练经验，把backbone和特征网络分开训的结果往往没有一起训的效果好。期盼您的解答！

**Comment by penghu-cs** [comment]
batch size的大小会影响对比学习性能，所以batch size不能过小了。backbone也是会优化的，只是刚开始的时候后面的哈希网络是随机初始化的，会影响前面预训练好的网络，所以会进行预热warmup_epoch个epoch，这个完成后，会进行微调。
