### ISSUE TITLE
Are  processed IAPR TC-12 and MS-COCO datasets available?

### ISSUE THREAD

**Issue by 19020011038** [penghu-cs/UCCH#3]
Hello, I think this paper is pretty good.  Could you please share the dataset of IAPR TC-12 and MS-COCO used in your paper?

**Comment by penghu-cs** [comment]
Thanks a lot for your attention. The data are available at:
IAPR-TC12:
link: https://pan.baidu.com/s/1c779W9I_E3szolBcPc_uTQ?pwd=f2ij
password: f2ij

MSCOCO:
link: https://pan.baidu.com/s/1h7tje0LdSH2x7pZxyvS3-A?pwd=s286
password: s286
