### ISSUE TITLE
Is there something wrong with the topk parameter in the function "fx_calc_map_multilabel_k"?

### ISSUE THREAD

**Issue by Cherishnoobs** [penghu-cs/UCCH#4]
The topK argument doesn't change the final result of the function, per se, because it always defaults to mAP@all rather than mAP@topK.

**Comment by penghu-cs** [comment]
In our work, we only compute mAP@all, thus the code cannot support different K.
You could try to revise the code as follows:
order = ord[i].reshape(-1)          ==>            order = ord[i].reshape(-1)[0: k]

Moreover, we also update the code. Hope this could help you.
