### ISSUE TITLE
 Could you please share the IAPR TC-12 and MS-COCO datasets used in your code? I am about to delay graduation due to not having these two datasets.

### ISSUE THREAD

**Issue by Junyanzhang** [penghu-cs/UCCH#7]

**Comment by penghu-cs** [comment]
Thanks a lot for your attention. The data are available at:
IAPR-TC12:
link: https://pan.baidu.com/s/1c779W9I_E3szolBcPc_uTQ?pwd=f2ij
password: f2ij

MSCOCO:
link: https://pan.baidu.com/s/1h7tje0LdSH2x7pZxyvS3-A?pwd=s286
password: s286
